#================================================================
#   Copyright (C) 2018 Sangfor Ltd. All rights reserved.
#   
#   文件名称：Makefile
#   创 建 者：jshunwang
#   创建日期：2018年01月09日
#   描    述：
#
#================================================================

include ../0_scripts/Makefile

all: $(Source)
	$(CC) $(CFLAGS) -o $(Objs) -c $(Source) 

clean:
	rm -rf $(Objs)
